name: Docker Image to Heroku

on:
  push:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:

      fail-fast: false
      matrix:
        python-version: ['3.6', '3.7', '3.8']

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: |
          python -c "import sys; print(sys.version)"
      - name: Installing Dep
        run: |
          pip install --no-cache-dir --upgrade -r requirements.txt
      - name: Running Tests
        run: |
          pytest
      - name: Test run the docker build
        run: |
          docker build . --file Dockerfile --tag fast-api-app:$(date +%s)

  deploy:

    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and push Docker to Heroku
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          DOCKERFILE_DIRECTORY: "."
          HEROKU_EMAIL: ${{ secrets.MY_EMAIL }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          DOCKERFILE_NAME: "Dockerfile"
          DOCKER_OPTIONS: "--no-cache"
        run: |
          cd ${DOCKERFILE_DIRECTORY}
          echo ${HEROKU_API_KEY} | docker login \
            --username=${HEROKU_EMAIL} \
            registry.heroku.com \
            --password-stdin
          docker build \
            --file ${DOCKERFILE_NAME} \
            ${DOCKER_OPTIONS} \
            --tag registry.heroku.com/${HEROKU_APP_NAME}/web .
          heroku container:push web --app ${HEROKU_APP_NAME}
          heroku container:release web --app ${HEROKU_APP_NAME}